### ISSUE TITLE
GitHub Pages

### ISSUE THREAD

**Issue by DevKowalsky** [JoaoVCustodioo/jsTestes#1]
Projeto > Configurações > Pages > Branch > Master > Save

Cria uma GitHub Pages e joga na Readme pra facilitar a visualização do seu desenvolvimento

**Comment by JoaoVCustodioo** [comment]
> Projeto > Configurações > Pages > Branch > Master > Save
> 
> Cria uma GitHub Pages e joga na Readme pra facilitar a visualização do seu desenvolvimento

Genio!
